### ISSUE TITLE
How to use Kqlmagic with non-public Azure clouds?

### ISSUE THREAD

**Issue by zakimaksyutov** [microsoft/jupyter-Kqlmagic#10]
It looks like that DraftClient gets hardcoded URL for Azure public cloud:

`_DATA_SOURCE = "https://api.applicationinsights.io"`

How to override it?

**Comment by zakimaksyutov** [comment]
For now I modified URL myself and followed the following instructions to make it work. It worked =)

```
git clone git://github.com/Microsoft/jupyter-Kqlmagic.git
cd ./jupyter-Kqlmagic
python setup.py install
```

**Comment by mbnshtck** [comment]
which cloud are you trying to access?

Michael

________________________________

**Comment by mbnshtck** [comment]
sovereign clouds were added in version 0.1.102. download latest version of Kqlmagic, and click on what's new in the Kqlmagic banner, to see the details on version 0.1.102
