### ISSUE TITLE
Kqlmagic does not initialize in directory with @ in dirname

### ISSUE THREAD

**Issue by neelaryan** [microsoft/jupyter-Kqlmagic#100]
#### Problem description

If the Jupyter notebook is present in a directory containing '@' in dirname, then ``%reload_ext Kqlmagic`` does not create the Kqlmagic folder in the same folder. Rather it creates a separate directory without '@' in name, and creates Kqlmagic folder there.

This is a problem if deployment / development is done in restricted environments where the user does not have permissions to create new folder at the same level where Jupyter is running. In such, the user will face the following error -

``PermissionError: [Errorno 13] Permission denied: '/home/user/dirwithsymbol'``

#### Steps to reproduce

- Create a folder ``/home/user/dirwith@symbol``
- Start Jupyter from ``/home/user/dirwith@symbol``
- Create a notebook and run the commands: ``import Kqlmagic`` and ``%reload_ext Kqlmagic``
- **Expected behavior**: new folder is created at ``/home/user/dirwith@symbol/kqlmagic``
- **Actual behavior**: new folder is created at ``/home/user/dirwithsymbol/kqlmagic``

**Comment by mbnshtck** [comment]
will be fixed soon.
