### ISSUE TITLE
Kqlmagic bug report #958c5e20-8ff1-4471-a690-3817dfb3e693

### ISSUE THREAD

**Issue by rchiodo** [microsoft/jupyter-Kqlmagic#102]
I'm getting this:

```
KqlError: Internal service error: Request aborted due to an internal service error.
Error details:
ClientRequestId='Kqlmagic.execute;5f188f8e-a990-4e53-bd5f-f1831bc34af3/0eee70ff-9bd7-4d23-a4f0-83551e815401/AzureDataExplorer', ActivityId='056b185c-3758-46f0-8baa-cc11e7e16023', Timestamp='2023-04-21T22:21:19.4718912Z'.
```

When executing this command:

```
%kql azureDataExplorer://code;cluster='https://ddtelvscode.kusto.windows.net/';database='VSCodeExt' -try_vscode-login
```

I do have access to that cluser and database as I can explore them in Azure Data Explorer.

**Comment by mbnshtck** [comment]
To get more visibity. Reset the Kernel, modify the cell, add  this option:  -!se to the statement, it should disable suppress error.

Also after you get the error, please execute %kql --bugreport
Please browse the output that it does not contain any secrets or data you don't want to share, and share it github

Micahel

**Comment by rchiodo** [comment]
It's suddenly working today. 

I used `%kql --bugreport` to generate this issue and there was no extra information. Although maybe if I had used `-!se`, I would have had more information last week.
