### ISSUE TITLE
Still based on deprecated msrestazure/ADAL - will there be an update?

### ISSUE THREAD

**Issue by OliverKleinBST** [microsoft/jupyter-Kqlmagic#103]
**Is your feature request related to a problem? Please describe.**
Still based on deprecated msrestazure/ADAL - will there be an update?

**Describe the solution you'd like**
Update to MSAL

**Describe alternatives you've considered**
Deprecate Plugin

**Additional context**
-

**Comment by mbnshtck** [comment]
Adal exist in the repo, but is not used. msal replaced adal in KqlMagic version 0.1.114 since 18 July, 2021
