### ISSUE TITLE
Notebook failed with error  (AttributeError: module 'plotly.graph_objs' has no attribute 'FigureWidget')

### ISSUE THREAD

**Issue by konabuta** [microsoft/jupyter-Kqlmagic#14]
Running "**%kql StormEvents | summarize count() by State | sort by count_ | limit 10 | render piechart title='my apple pie'**"  fails with error. It seems plotly version related issue. Any workaround ?

[Kqlmagic Quick Start](https://github.com/microsoft/jupyter-Kqlmagic/blob/master/notebooks/QuickStart.ipynb)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/miniconda3/envs/kqlmagic/lib/python3.6/site-packages/Kqlmagic/results.py in _repr_html_(self)
    340 
    341             if self.is_chart():
--> 342                 self.show_chart(**self.options)
    343             else:
    344                 self.show_table(**self.options)

~/miniconda3/envs/kqlmagic/lib/python3.6/site-packages/Kqlmagic/results.py in show_chart(self, **kwargs)
    460         if window_mode and not options.get("button_text"):
    461             options["button_text"] = "popup " + self.visualization + ((" - " + self.title) if self.title else "") + " "
--> 462         c = self._getChartHtml(window_mode)
    463         if c.get("body") or c.get("head"):
    464             html = Display.toHtml(**c)

~/miniconda3/envs/kqlmagic/lib/python3.6/site-packages/Kqlmagic/results.py in _getChartHtml(self, window_mode)
    541         # First column is color-axis, second column is numeric
    542         if self.visualization == VisualizationValues.PIE_CHART:
--> 543             figure_or_data = self._render_piechart_plotly(self.visualization_properties, " ")
    544             # chart = self._render_pie(self.visualization_properties, " ")
    545 

~/miniconda3/envs/kqlmagic/lib/python3.6/site-packages/Kqlmagic/results.py in _render_piechart_plotly(self, properties, key_word_sep, **kwargs)
   1149             ],
   1150         )
-> 1151         fig = go.FigureWidget(data=data, layout=layout)
   1152         return fig
   1153 

AttributeError: module 'plotly.graph_objs' has no attribute 'FigureWidget'

[{'State': 'TEXAS', 'count_': 4701},
 {'State': 'KANSAS', 'count_': 3166},
 {'State': 'IOWA', 'count_': 2337},
 {'State': 'ILLINOIS', 'count_': 2022},
 {'State': 'MISSOURI', 'count_': 2016},
 {'State': 'GEORGIA', 'count_': 1983},
 {'State': 'MINNESOTA', 'count_': 1881},
 {'State': 'WISCONSIN', 'count_': 1850},
 {'State': 'NEBRASKA', 'count_': 1766},
 {'State': 'NEW YORK', 'count_': 1750}]

![image](https://user-images.githubusercontent.com/3815677/59144264-3ed88d80-8a10-11e9-9246-a4eb8a042c1e.png)

**Comment by mbnshtck** [comment]
can you please send me the full out cell with the error stack.
Michael

Michael

________________________________

**Comment by mbnshtck** [comment]
Pls send me the following information :
1. what is the environment: jupyter notebook or lab, or ipython. is it desktop or service or hub. what version of kernel you use. what version of plotly is installed.

Thanks, Michael

Michael

________________________________

**Comment by konabuta** [comment]
1. I use **jupyter notebook** on my **desktop** (macbook). My conda env is **Python 3.6.8**. Plotly version is plotly==3.10.0.

I attached output of pip freeze.
[pipfreeze.txt](https://github.com/microsoft/jupyter-Kqlmagic/files/3268619/pipfreeze.txt)

**Comment by konabuta** [comment]
Full stack is as follows and see the jupyter notebook file.



---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/miniconda3/envs/kqlmagic/lib/python3.6/site-packages/Kqlmagic/results.py in _repr_html_(self)
    340 
    341             if self.is_chart():
--> 342                 self.show_chart(**self.options)
    343             else:
    344                 self.show_table(**self.options)

~/miniconda3/envs/kqlmagic/lib/python3.6/site-packages/Kqlmagic/results.py in show_chart(self, **kwargs)
    460         if window_mode and not options.get("button_text"):
    461             options["button_text"] = "popup " + self.visualization + ((" - " + self.title) if self.title else "") + " "
--> 462         c = self._getChartHtml(window_mode)
    463         if c.get("body") or c.get("head"):
    464             html = Display.toHtml(**c)

~/miniconda3/envs/kqlmagic/lib/python3.6/site-packages/Kqlmagic/results.py in _getChartHtml(self, window_mode)
    541         # First column is color-axis, second column is numeric
    542         if self.visualization == VisualizationValues.PIE_CHART:
--> 543             figure_or_data = self._render_piechart_plotly(self.visualization_properties, " ")
    544             # chart = self._render_pie(self.visualization_properties, " ")
    545 

~/miniconda3/envs/kqlmagic/lib/python3.6/site-packages/Kqlmagic/results.py in _render_piechart_plotly(self, properties, key_word_sep, **kwargs)
   1149             ],
   1150         )
-> 1151         fig = go.FigureWidget(data=data, layout=layout)
   1152         return fig
   1153 

AttributeError: module 'plotly.graph_objs' has no attribute 'FigureWidget'

[Archive.zip](https://github.com/microsoft/jupyter-Kqlmagic/files/3268631/Archive.zip)

**Comment by mbnshtck** [comment]
Hi,
Please install ipywidgets, and run again, and let me know if it solved your problem.
Michael

**Comment by mbnshtck** [comment]
Fixed in version 0.1.99
Pls try and let me know.
Thanks, Michael

**Comment by konabuta** [comment]
Solved ! Thank you for your help.

**Comment by nnadiabfata** [comment]
i always have the same problem. i install conda pip and i uninstall different versions of plotly i don't know what's exactly the problem:
here are my errors  

AttributeError: module 'plotly.files' has no attribute 'FILE_CONTENT'


ModuleNotFoundError: No module named 'plotly.plotly'

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\33788\\Anaconda3\\lib\\site-packages\\plotly\\package_data\\templates\\plotly.json'

please can you help me i based my project analysis on iplot it works so long till i changed the version to make the map the other plots with old version don't work !!!!!!
