### ISSUE TITLE
"popup schema" button doesn't work when path has spaces

### ISSUE THREAD

**Issue by jruales** [microsoft/jupyter-Kqlmagic#15]
When running a notebook that is located in a file path that has spaces in it, the temporary html files that are generated with the table schema have the spaces replaced with underscores. However, when clicking on the "popup schema" button, the URL that is generated doesn't have the replacement of spaces to underscores, so this causes a 404 page to be displayed.

**Comment by mbnshtck** [comment]
thx, for letting me know about this issue. will fix it.
Michael

Michael

________________________________

**Comment by mbnshtck** [comment]
resolved in version 0.1.106
