### ISSUE TITLE
Incorrect html escaping of info messages

### ISSUE THREAD

**Issue by jruales** [microsoft/jupyter-Kqlmagic#16]
In this line: https://github.com/microsoft/jupyter-Kqlmagic/blob/4e5dce7911fcdc90eff72fdfc7aa0fa9494af92c/azure/Kqlmagic/display.py#L270

the `.replace(" ", "&nbsp")` is missing a semicolon after the nbsp.

**Comment by jruales** [comment]
The issue is clearly visible when we run a notebook using Papermill:
![PapermillOutput](https://user-images.githubusercontent.com/1588988/60231433-01686280-984e-11e9-9418-7c43aee9f6e5.png)

**Comment by mbnshtck** [comment]
thanks, will fix shortly. 
BTW, working on support for papermill, will be deployed end of next week.

**Comment by jruales** [comment]
This issue was already fixed with PR #18 .

Regarding papermill support: nice! Although I wonder what exactly this support will entail, since we can already run notebooks with Kql from papermill? Will it allow passing the connection string from papermill directly? Currently we've been using a workaround where we inject a `%run` magic at the start of the notebook to initialize Kqlmagic with a connection string (that we have in a separate notebook), before running the notebook. We also disable the pretty html errors so that we have the errors as exceptions when run the notebook with papermill
