### ISSUE TITLE
Feature Request: Include "Open in Azure Data Explorer" link next to result

### ISSUE THREAD

**Issue by jruales** [microsoft/jupyter-Kqlmagic#19]
An "Open in Azure Data Explorer" link next to results would allow continuing the exploration of Kusto data in Data Explorer. This is especially important when the query has Python variables replaced into it, since then it's not possible to simply copy and paste the query into Data Explorer

**Comment by mbnshtck** [comment]
Good idea, will add it to our feature wish list.
Thank you,
Michael

**Comment by jruales** [comment]
Another similar ask is to have a way of showing the replaced query directly in the notebook, for example having a tabbed view that shows the table or plot on one tab and the underlying, replaced query on the other one

**Comment by mbnshtck** [comment]
What do you mean by replaced query?
The query after it was parametrized? This exist: _kql_raw_result_.parametrized_query

Michael

**Comment by jruales** [comment]
I understand that `_kql_raw_result_.parametrized_query` exists. What I'm suggesting is to automatically show the parameterized query whenever we should a table or plot. As in, to have some button or tab mechanism to reveal/hide the parameterized query. This would have two advantages: 
* the possibility for having Kusto syntax highlighting in the shown query
* not having to execute the extra command "_kql_raw_result_.parametrized_query".
For us, it will be especially helpful since we're executing the notebooks via Papermill and in the process are removing the input cells, so it would be an easy was to understand what Kusto query a visualization came from

**Comment by mbnshtck** [comment]
Excellent idea, will add this as an option to the query.
Michael

**Comment by mbnshtck** [comment]
This feature was added in Kqlmagic version 0.1.102
To use it use option -show_query (or abbreviation -sq) with the query. For example:
                 %kql -sq {your query}

If you want it to be the default you can change the default as follow:
                 %config Kqlmagic.show_query=True

You can also make it the default outside of the notebook, by setting the environment variable:
                  KQLMAGIC_CONFIGURATION=’show_query=True’

btw: KQLMAGIC_CONFIGURATION environment variable can have many options set to custom defaults, separated by ‘;’ for example:
                  KQLMAGIC_CONFIGURATION=’show_query=True; show_query_time=False’

Michael

**Comment by jruales** [comment]
I've just tried it and it works great!
I'm wondering if you've considered adding the "Open in Azure Data Explorer" link? the format for those URLs is relatively simple, since it's possible to simply include the UTF-8 base64 encoded query in the URL itself

**Comment by mbnshtck** [comment]
Feature was added in version 0.1.103. Download latest version of Kqlmagic, click on 'what's new button in the Kqlmagic init banner, to see the details of version 0.1.103. To support it two option were added, show_query_link (default False, abbreviation sql) and query_link_destination (default "Kusto.webexplorer", abbreviation dlq). To activate it on a query use %kql -sql {your query} you can also modify the defaults using %config
