### ISSUE TITLE
Kqlmagic not installed in Azure Notebooks by default

### ISSUE THREAD

**Issue by jruales** [microsoft/jupyter-Kqlmagic#22]
The tutorial *"Use a Jupyter Notebook and Kqlmagic extension to analyze data in Azure Data Explorer"* states that it's not necessary to install Kqlmagic on Azure Notebooks.

However, when I try to run `%reload_ext Kqlmagic` from a fresh Azure Notebook, I get an error: `ImportError: No module named 'Kqlmagic'`

**Comment by mbnshtck** [comment]
I just tried on the free Azure Notebooks, and it was fine. Are you using a different flavor of Azuee Notebooks?
Michael

**Comment by jruales** [comment]
Tried out different things, and it seems like Kqlmagic is pre-installed for Python 3.6 Notebooks but not for Python 3.5 ones
![image](https://user-images.githubusercontent.com/1588988/62671612-74d0ba00-b94c-11e9-82d8-e71d4c922005.png)

**Comment by mbnshtck** [comment]
its because Kqlmagic requires python version 3.6 and up.
Muchael

Michael

________________________________

**Comment by jruales** [comment]
Got it. In that case, the Minimum Requirements mentioned in the README.md are incorrect:
![image](https://user-images.githubusercontent.com/1588988/62726507-3844a300-b9cc-11e9-9716-2cac854894aa.png)

**Comment by jruales** [comment]
Closing this issue
