### ISSUE TITLE
Displayed KQL error messages are difficult to read and act upon

### ISSUE THREAD

**Issue by jruales** [microsoft/jupyter-Kqlmagic#34]
When a query has a syntax error, the output message is very difficult to read because of all the "\n" literals and the fact that it's a flat JSON text. I wish that Kqlmagic made it easier to understand these errors. For example, Kqlmagic could parse the JSON and print the different JSON properties separately, using the correct newline replacements and so on.

![image](https://user-images.githubusercontent.com/1588988/64468553-e67e5e00-d0da-11e9-8e9d-b9d95050fb4e.png)

**Comment by mbnshtck** [comment]
you are right, it is an old ask, will do it in one of the next versions.

Michael

________________________________

**Comment by mbnshtck** [comment]
fixed in version 0.1.105

Michael

________________________________
