### ISSUE TITLE
The "plot_package='matplotlib'" config is not honored

### ISSUE THREAD

**Issue by jruales** [microsoft/jupyter-Kqlmagic#35]
I have set the `plot_package` config to "matplotlib":

![image](https://user-images.githubusercontent.com/1588988/64469898-1a637e80-d0ef-11e9-8fa9-588dd34b8309.png)

However, timecharts are still rendered in Plotly

**Comment by mbnshtck** [comment]
matplotlib was supported in the past. currently it is not working (no much demand for it) , will bring it back in one of the future versions

Michael

________________________________

**Comment by jruales** [comment]
Got it. If it’s not implemented, then why not remove or hide the option to avoid confusion? Or at least call out in the config list that it’s not available?

**Comment by mbnshtck** [comment]
removed in version 0.1.105

Michael

________________________________
