### ISSUE TITLE
Feature Request: Being able to override "Application" metadata

### ISSUE THREAD

**Issue by jruales** [microsoft/jupyter-Kqlmagic#44]
Currently, all queries run by Kqlmagic appear as having an "Application" of "Kqlmagic" when we see the KQL queries that it has executed by using ".show queries". We would like to request the ability to override this "Application" metadata property with a custom value. This would be set for Kqlmagic globally, not per-query.

Context:
We have a service that runs Jupyter notebooks automatically using an AAD app for authentication. Because of this, all KQL queries made by the Jupyter notebooks appear with the same App ID and Application, which makes it difficult for us to identify the origin of expensive queries that might affect the cluster health. We would like to use the Application field to include the ID of the job that is running the notebook. This way, it will be very straightforward for us to find jobs that are using too many resources.

**Comment by mbnshtck** [comment]
hi,
the kqlmagic application is used internally to monitor kqlmagic usage. So it is important to keep tagging the queries with "kqlmagic".
However, I can concatinate a custom Application name. Will it be good enough for your scenario?

Michael

Michael

________________________________

**Comment by jruales** [comment]
Yep, this option still works for us, since we'll still be able to extract the id from there

**Comment by mbnshtck** [comment]
Implemented. see version 0.1.107 new feature request-tags
