### ISSUE TITLE
 ImportError: this version of pandas is incompatible with numpy < 1.12.0 on databricks cluster python 3

### ISSUE THREAD

**Issue by cosh** [microsoft/jupyter-Kqlmagic#45]
I used Kqlmagic 0.1.106.post2 with and Azure Databricks 5.5 cluster (python 3)

`ImportError: this version of pandas is incompatible with numpy < 1.12.0
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<command-2514987408507417> in <module>()
----> 1 get_ipython().magic('reload_ext Kqlmagic')

/databricks/python/lib/python3.5/site-packages/IPython/core/interactiveshell.py in magic(self, arg_s)
   2203         Out[2]: ('x.l', ['x.ljust', 'x.lower', 'x.lstrip'])
   2204         """
-> 2205 
   2206         # Inject names into __builtin__ so we can complete on the added names.
   2207         with self.builtin_trap:

/databricks/python/lib/python3.5/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line)
   2124 
   2125     def _indent_current_str(self):
-> 2126         """return the current level of indentation as a string"""
   2127         return self.input_splitter.get_indent_spaces() * ' '
   2128 

<decorator-gen-66> in reload_ext(self, module_str)
`

**Comment by mbnshtck** [comment]
custom magics are not supported in databricks notebooks.
However, you can use instead the jupyter notebooks environment with a connector to databricks

Michael

________________________________
