### ISSUE TITLE
the service loganalytics is not supported in cloud None

### ISSUE THREAD

**Issue by MauRiEEZZZ** [microsoft/jupyter-Kqlmagic#46]
I try to configure Kqlmagic using environment variables
I have setup the connectionstring and checked if they work.
While running %reload_ext Kqlmagic the error "the service loganalytics is not supported in cloud None" is returned.

**Comment by mbnshtck** [comment]
please send me the env variables you set with the values. and describe what you want to achieve.
Michael

Michael

________________________________

**Comment by MauRiEEZZZ** [comment]
Hi Michael,

I set the KQLMAGIC_CONNECTION_STR using a couple of other variables.

<img width="756" alt="image" src="https://user-images.githubusercontent.com/9781801/66330752-4dd53b00-e931-11e9-87cd-bb99307393d0.png">

<img width="721" alt="image" src="https://user-images.githubusercontent.com/9781801/66331482-f768fc00-e932-11e9-87f4-409279a84ceb.png">

And then I simple run %reload_ext Kqlmagic
<img width="750" alt="image" src="https://user-images.githubusercontent.com/9781801/66330798-69d8dc80-e931-11e9-820f-e5fb015fa902.png">

If I copy paste the value it just reloads normal:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/9781801/66331618-4020b500-e933-11e9-9b5c-5778081140ac.png">

I was thinking to work around this but my python skills limit me doing this on the %kql loganalytics:// line.

**Comment by mbnshtck** [comment]
Thank you for reporting the bug.
I fixed it (fix is deployed in version 0.1.107.post1)
upgrade your Kqlmagic

**Comment by MauRiEEZZZ** [comment]
You are welcome!

I tested it but to me it didn't start the authentication challenge.

I changed the values but the outcome is what I have on screen.
<img width="569" alt="image" src="https://user-images.githubusercontent.com/9781801/66337344-3ef58500-e93f-11e9-9ad9-39c3e22dd2ef.png">

Did I do something wrong then?

**Comment by MauRiEEZZZ** [comment]
I figured out how I can use the env variable in a magic command. 
This proves my connection string is correct, right?
<img width="514" alt="image" src="https://user-images.githubusercontent.com/9781801/66337745-04d8b300-e940-11e9-9006-14fa0e6a402c.png">

**Comment by MauRiEEZZZ** [comment]
You are welcome!

It works perfect!

The challenge will popup at the moment the first query is send.

Thank you!
