### ISSUE TITLE
Feature Request: Simpler Query Parameterization

### ISSUE THREAD

**Issue by jruales** [microsoft/jupyter-Kqlmagic#48]
Currently, it's necessary to add let statements in a very specific way at the start of the query in order to use Python variables within a KQLMagic query. This can feel unnatural and can cause the query to become verbose. Would it be possible to have a simpler way to parameterize queries?

One way that comes to mind is the way that Kusto.Explorer does it, which is to surround parameters with curly braces. basically, anything that matches something like the regex /{[\w-]+}/ would be replaced with the Python variable of the same name, so the query `%kql print {message1} + {message2}` would work, instead of having to do `%kql let message1 = message1; let message2 = message2; print message1 + message2`

**Comment by mbnshtck** [comment]
added in version 0.1.112
### New Feature -enable_curly_brackets_params option

    - when set, strings within curly brackets will be evaluated as a python expression, and if evaluation succeeds result will replace the string (including the curly brackets).
    - if evaluation fails it won't be modified, including the curly brackets.
    - to escape curly brackets they must be doubled {{something}}.
    - Abbreviation: 'ecbp'
    - type mapping from python to KQL types is as follows:
        - int -> long
        - float -> real
        - str -> string
        - bool -> bool
        - datetime -> datetime
        - timedelta -> timespan
        - dict, list, set, tuple -> dynamic (only if can be serialized to json)
        - pandas dataframe -> view table
        - None -> null
        - unknown, str(value) == 'nan' -> real(null)
        - unknown, str(value) == 'NaT' -> datetime(null)
        - unknown str(value) == 'nat' -> time(null)
        - other -> string
    - for example:
        - count = 10
        - interval = timedelta(days=5, hours=3)
        - %kql -ecbp requests | where timestamp > ago({interval}) | limit {count+5}

        - p_dict = {'p_limit':20, 'p_not_state':'IOWA'}
        - %%kql
            - -ecbp -params_dict=p_dict
            - StormEvents
            - | where State != {p_not_state}
            - | summarize count() by State
            - | sort by count_
            - | limit {p_limit}
