### ISSUE TITLE
Help for 'options' topic returns not implemented yet

### ISSUE THREAD

**Issue by derekbekoe** [microsoft/jupyter-Kqlmagic#56]
```
%kql --help "options" 
Sorry, not implemented yet.
```

**Comment by mbnshtck** [comment]
till implemented, use: %kql --config
Michael

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by derekbekoe** [comment]
Seems odd that there isn't topic help for "options" while there is for every other one but `%kql --config` did help thanks so will close the issue.
