### ISSUE TITLE
MFA doesn't work in VS code's Jupyter extension

### ISSUE THREAD

**Issue by chenfeibo** [microsoft/jupyter-Kqlmagic#64]
Hi,

I'm using KqlMaggic version 0.1.113. I can successfully do MFA in Jupyter notebook running in a browser. But when try it in VS code's Jupyter extension, it doesn't work. 

The "Copy code to clipboard and authenticate" button appears, after clicking it the code was copied into clipboard but no page was opened for authentication. Not sure if it's an issue of KqlMargic or the Jupyter extension.

Thanks,
Feibo

**Comment by mbnshtck** [comment]
To start troubleshoot it, please send me which vscode version you use and  what os, and other info that you think might help to reproduce it

**Comment by chenfeibo** [comment]
> To start troubleshoot it, please send me which vscode version you use and what os, and other info that you think might help to reproduce it

I'm using vs code 1.52.1. Tried it on both WSL 2.0 based on Ubuntu 20.04.1 LTS and a Jupyter Notebook server built by Azure Machine Learning Service, which is based on Ubuntu 16.04.7 LTS.

**Comment by mbnshtck** [comment]
please try to set KQLMAGIC_NOTEBOOK_APP environment variable to visualstudiocode before you load Kqlmagic:

%env KQLMAGIC_NOTEBOOK_APP=visualstudiocode 
%reload_ext Kqlmagic

and let me know whether it solved the problem

**Comment by chenfeibo** [comment]
Yes, this works! Thank you so much Michael!

**Comment by mbnshtck** [comment]
Can you please run %env in your notebook, before you load Kqlmagic, and send me the output (make sure to remove/obfuscate secrets if exist). please send it directly to my email: mbnshtck@gmail.com
I would like to see whether visual studio code has any environment variables on these Linux variants that can be used as a signature to auto-detect it in the future
Thanks

**Comment by chenfeibo** [comment]
sent.

**Comment by mbnshtck** [comment]
Thank you
