### ISSUE TITLE
Help menu injections prevents automatic reloading

### ISSUE THREAD

**Issue by rwrife** [microsoft/jupyter-Kqlmagic#69]
This function https://github.com/microsoft/jupyter-Kqlmagic/blob/e483b34c605a2d332e078ea74e6015dad5f89d77/azure/Kqlmagic/kql_magic_core.py#L380 prevents kqlmagic from being automatically loaded into the notebooks via ipython_config.py (add code to execute %reload_ext Kqlmagic) in Jupyter.  Oddly enough it works fine in the ipython cli interface, but the kernel is started from inside of Jupyter Labs it throws and error because Help_html.add_menu_item is not defined.  I'd suggest wrapping the code inside of some conditional or removing it entirely (which is what I did).

**Comment by mbnshtck** [comment]
thank you for reporting about this issue. Will be fixed in following dev version and full release

**Comment by mbnshtck** [comment]
Done in version 0.1.114
