### ISSUE TITLE
Running kqlmagic in a python script.

### ISSUE THREAD

**Issue by amaljithkuttamath** [microsoft/jupyter-Kqlmagic#73]
expectation: is to use kql function in a python script.

```python
from Kqlmagic import kql

kql("""appinsights://appid='xxx'; appkey='xxx'; alias='xxx' """)
page_view = f'''pageViews '''

kql(page_view).to_dataframe())
```

This works, however, is there a way to suppress the **popup schema** message (html) after **authentication** ?

opens in file location _C:/Users/xxx/kqlmagic/temp_files/xxx/xxx/xxx.html_

**Comment by lesleyxyz** [comment]
I am also wondering this, using Kqlmagic doesn't seem to have an easy way to use in regular python, which is weird because how else would I integrate this in business applications

**Comment by mbnshtck** [comment]
yes, you van set """appinsights://appid='xxx'; appkey='xxx'; alias='xxx' """ option to false. Either with the environment variable KQLMAGIC_CONFIGURATION="auto_popup_schema=False" or when calling kql methos set it to False
kql("""appinsights://appid='xxx'; appkey='xxx'; alias='xxx' """, options={"auto_popup_schema": False})

**Comment by mbnshtck** [comment]
yes, you can set 'auto_popup_schema' option to false. Either with the environment variable KQLMAGIC_CONFIGURATION="auto_popup_schema=False" or when calling kql method set it to False
kql("""appinsights://appid='xxx'; appkey='xxx'; alias='xxx' """, options={"auto_popup_schema": False})

**Comment by amaljithkuttamath** [comment]
Thank you @mbnshtck,

However, My use-case mostly is around Application Insights, Fortunately I found this REST-API implementation by Microsoft, (saved my day)
[Application Insights RESTAPI](https://dev.applicationinsights.io/reference)

Just leaving it out here, for anyone with a similar use-case.
