### ISSUE TITLE
display_limit is incorrectly ignored when display_limit = 0

### ISSUE THREAD

**Issue by alexchandel** [microsoft/jupyter-Kqlmagic#82]
`%config Kqlmagic.display_limit = 0` should silence all rows, leaving only the `Done (time): X records` printed.  Instead, `display_limit` is completely ignored, and all records are printed.  Please fix this.

Occurs in version 0.1.114.post8 and probably earlier versions.

**Comment by mbnshtck** [comment]
I will fix it in 0.1.114.post9, but beware that  display_limit set to 0, will display an empty table (a line of colum names followed by a note). I added a new feature, if you set display_limit to a negative number, it won't display the table and won't display the note.
