### ISSUE TITLE
Parsing fails when trying to connect to database with space in name

### ISSUE THREAD

**Issue by joslevin** [Microsoft/jupyter-Kqlmagic#9]
Trying to connect to a database that has a space in the name fails. Example:

`%kql azuredataexplorer://code;cluster='my-cluster';database='Database WithSpaceInName';Alias='IDontCare'`

returns 
`failed to set database, due to invalid str value 'Database.`

Note that connecting to this database works correctly in other applications. If I have some free bandwidth, I'll try to dig into why this happens - but I'd just like to bring it to your attention now.

**Comment by mbnshtck** [comment]
Fixed
