### ISSUE TITLE
Kqlmagic | AAD Device Code authentication fails due to a Window-ism when device_code_login_notification=browser_reference

### ISSUE THREAD

**Issue by David-Noble-at-work** [microsoft/jupyter-Kqlmagic#90]
Here is the error. Please remove this Window-ism: [os.startfile](https://docs.python.org/3/library/os.html).

<img width="1957" alt="image" src="https://user-images.githubusercontent.com/3037615/169344675-40346f00-2035-4f91-9357-e0d8ce71248e.png">

**Comment by David-Noble-at-work** [comment]
Are you guys actively looking at issues? I'm Microsoft and available for a remote debugging session on macOS, if you would like. It seems to me you've let some Window-isms creep in. You also don't work very well with JetBrains. I'm here to help, if you'd like.

**Comment by mbnshtck** [comment]
will be fixed in next update

**Comment by David-Noble-at-work** [comment]
Awesome. I'm happy to see you working on this. When's the next update? Any guesstimates?
